### ISSUE TITLE
Migrate away from cargo-xbuild

### ISSUE THREAD

**Issue by jonlamb-gh** [auxoncorp/ferros#75]
As of `nightly 2020–07–15`, cargo has its own feature for cross compiling the sysroot (see [build-std](https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#build-std)) in a `.cargo/config.toml`
```toml
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
```
We no longer need to use `cargo-xbuild` to do this.
